# Generated by Django 2.0.6 on 2021-01-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_published',
            new_name='is_publish',
        ),
    ]
