# Generated by Django 2.0.6 on 2021-01-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210109_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_publish',
            new_name='is_published',
        ),
    ]
